FROM python:3.10-slim

WORKDIR /app

# Instalamos dependencias
RUN pip install --no-cache-dir \
    python-telegram-bot[asyncio] \
    httpx

# Copiamos el código
COPY telegram_bot.py .

# Entrypoint
CMD ["python", "telegram_bot.py"]
